language: python

# Add existing Python Versions
python:
  - "3.5"
  - "3.6"
  - "3.7"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

install: pip install .
script: pytest test
notifications:
  email:
    - yeejiarongg@gmail.com
